function onLoad()
  params = {
    click_function = "attemptPurchase",
    function_owner = self,
    position = {0, 1, 0},
    rotation = {0, 0, 0},
    width = 500,
    height = 500,
    color = {0.5, 0.5, 0.5, 0},
    tooltip = "Automatically build card.",
  }
  self.createButton(params)
end

function attemptPurchase(obj, color)
  -- calls function that handles "purchasing" a quest card
  getObjectFromGUID("6425d0").call("purchaseCard", color)
end