local placement_pos = { - 14.50, 0.97, - 7.00}

--none: player has not passed
--round: player passes on the current bid
--all: player permenantly passed discovery phase
local passes = {}

local hasStartedBid = {}

local bid_order = {}

-- the value of the current bid
local bid = 1
-- the color of the player with highest bid
local bidder = nil
-- the round number which only increases after each player gets to bid once
-- controls the cost of starting bids
local bid_round = 1
-- the card being bid upon
local bid_object = nil
--tracks the place to send card back if a player passes
local bid_card_start_pos = nil
local collider_board = nil
local bid_card_guids = {}
local three_ev_bag = nil
local turn_control = nil

function onLoad()
  three_ev_bag = Global.getVar("three_ev_bag")
  turn_control = getObjectFromGUID("90061a")
  self.interactable = false
  local players = getSeatedPlayers()
  for i = 1, #players do
    passes[players[i]] = "none"
    hasStartedBid[players[i]] = 0
  end
end

function onEndTurn(player)
  local player_color = player.color

  --if the player ends their turn without bidding on a card
  if bidder == nil then
    playerPass(player, "all")
    --if the player ends their turn but a bid already exists
  elseif bidder ~= player_color then
    playerPass(player, "round")
  else
    turn_control.call("next_turn")
  end
end

--checks if player has the money and it is their bid turn, then increases the bid by +1
function increaseBid(player)
  local current_phase = Global.getVar("current_phase")
  if current_phase == 4 then
    local player_color = player.color
    local player_coins = three_ev_bag.call("calculateCoins", player_color)

    if player_color ~= bidder then
      broadcastToAll(player_color.. ". It is not your turn to increase the bid or you haven't placed your physicist on a card yet!")
    end

    if player_coins >= bid + 1 then
      bid = bid + 1
      collider_board.UI.setAttribute("discovery_bid", "text", "Bid: " ..bid)
    else
      broadcastToAll(player_color.. ". You do not have enough coins to make this increased bid!")
    end
  else
    broadcastToAll("Wrong phase, this button should not be available to you!")
  end

end

--called when a player clicks a pass button
-- type: the pass type "round" or "all"
function playerPass(player, type)
  local collider_board = getObjectFromGUID("1f72b6")
  local skip_player = turn_control.call("get_skip_player")
  local player_order = turn_control.call("get_player_order")

  --reset everything if bidder is passing
  -- check if there is someone left to bid happens below
  -- return card to pile or otherwise (NOT COMPLETE)
  if player.color == bidder then
    bid = bid_round
    bidder = nil
    --return bid card to its original position
    if bid_object ~= nil and bid_card_pos ~= nil then
      bid_object.setPositionSmooth({bid_card_pos[1], 2, bid_card_pos[3]})
    end
    bid_object = nil
    --return player pawn as well
    collider_board.call("kickLowerBid", player.color)
  end

  local current_phase = Global.getVar("current_phase")
  if current_phase == 4 then
    passes[player.color] = type
    -- cannot remove the final player from the turn system so try ending the bid
    if skip_player ~= nil and #skip_player >= #player_order - 1 then
      attemptEndBid()
      return
    end

    --remove this player from the internal turn control for this bidding phase
    turn_control.call("add_skip", player.color)

    --set for bid amount tracking that if a player passes they've has a chance at bidding
    if type == "all" then
      hasStartedBid[player.color] = 1
    end

    attemptEndBid()
  else
    broadcastToAll("Wrong phase, this button should not be available to you!")
  end
end

local bid_setup = false
--if its a deck take the card
-- collision {["color"] = , ["object"] =}
function calculateBid(collision)
  -- deals with re-trigger from moving card to bid position
  if bid_setup then
    bid_setup = false
    return
  end

  local bid_card_pos = { - 18.7, 1, 0}

  local player_color = collision["player_color"]
  local object = collision["object"]
  local figurine_guids = Global.getTable("figurine_guids")
  local physicist = getObjectFromGUID(figurine_guids[player_color])
  local current_player = turn_control.call("get_current_turn")

  if player_color ~= current_player then
    broadcastToAll("It is not your turn to bid " ..player_color)
    collider_board.call("kickLowerBid", player_color)
    return
  end

  -- exit the function if player is just moving figurine on the card
  if bidder == player_color then
    return
  end

  -- prevent player from bidding on their own cards or game decks
  if object.type == "Deck" then
    --if its a Deck we fetch the GUID of the first item
    if bid_card_guids[object.getObjects()[1].guid] == nil then
      broadcastToAll("You cannot bid on this card/deck!")
      return
    end
  else
    if bid_card_guids[object.getGUID()] == nil then
      broadcastToAll("You cannot bid on this card/deck!")
      return
    end
  end

  local bid_card = nil;
  -- set bid_card to bid_object
  if bid_object ~= nil then
    bid_card = bid_object
  end

  -- if no bid is set, get the bid_object and set it, move card to bid location
  if bid_object == nil then
    if object ~= nil and object.type == "Deck" then
      --track original position
      bid_card_start_pos = object.getPosition()
      bid_card = object.takeObject({
        position = bid_card_pos,
        smooth = true,
      })
    else
      bid_card = object
      --track original position
      bid_card_start_pos = object.getPosition()
      bid_card.setPositionSmooth(bid_card_pos)
    end
    bid_setup = true
    physicist.setPositionSmooth({bid_card_pos[1], 2, bid_card_pos[3]})
  end

  --if its initial setup we set the bid_object
  if bid_object == nil then
    bid_object = bid_card
  end


  local current_phase = Global.getVar("current_phase")
  local player_coins = three_ev_bag.call("calculateCoins", player_color)
  collider_board = Global.getVar("collider_board")

  --this error will likely never happen
  -- if round is Discovery Round
  if current_phase ~= 4 then
    broadcastToAll("It is not the Discovery phase, you cannot bid on ejection cards!")
    return
  end

  --check to make sure the player can afford the bid they're making
  -- what is going on here?
  if player_coins < bid + 1 then
    local type = "bid"
    if passes[player_color] == "none" then
      if player_coins < bid_round + 1 then
        passes[player_color] = "all"
        type = "ejection phase"
      else
        passes[player_color] = "round"
      end
    end
    broadcastToAll("You do not have enough coins to bid. You will be automatically passed for this " ..type)
    collider_board.call("kickLowerBid", player_color)
    return
  end

  --check to ensure the correct card is being bid on
  if bid_object.getName() == bid_card.getName() then
    --if a new player is bidding and hasn't passed
    if player_color ~= bidder and passes[player_color] == "none" then
      -- kick other bid figurine (physicist)
      if bidder ~= nil then
        collider_board.call("kickLowerBid", bidder)
      end

      bidder = player_color
      bid = bid + 1
      collider_board.UI.setAttribute("discovery_bid", "text", "Bid: " ..bid)

      --attemptEndBid() -- does this need to be here
    else
      broadcastToColor("You already have highest bid or have passed this round or you are trying to bid on another card. Only one card bid at a time.", player_color)
    end
  end
end

function attemptEndBid()
  local passCount = 0
  local players = getSeatedPlayers()
  local bid_count = 0
  --counting number of players that have passed
  for i = 1, #players do
    local player_color = players[i]
    local pass_value = passes[player_color]
    if pass_value == "all" or pass_value == "round" then
      passCount = passCount + 1
    end
  end

  -- if all but one player has passed complete the bid
  if passCount == #players - 1 and bidder ~= nil then
    --give card to player and reset bid variables
    bid_card_guids[bid_object.getGUID()] = nil
    bid_object.deal(1, bidder)

    collider_board.call("kickLowerBid", bidder)

    local one_ev_bag = Global.getVar("one_ev_bag")
    one_ev_bag.call("spendCoins", {["cost"] = bid, ["player_color"] = bidder})

    hasStartedBid[bidder] = 1
    for i = 1, #players do
      bid_count = bid_count + hasStartedBid[players[i]]
    end

    local player_order = turn_control.call("get_player_order")
    local player_index = Global.getTable("player_index")
    local order_player = turn_control.call("get_order_player")

    -- clear skips first, then re-add players who have skipped the whole phase
    turn_control.call("clear_skip")
    passCount = 0

    -- has everyone had a chance to bid at the current starting bid value?
    -- if so increment the round which increases the starting bid by 1
    -- check which players should still be skipped by internal turn controls
    -- resetting turns
    if bid_count >= #players then
      bid_round = bid_round + 1
      for i = 1, #players do
        if passes[players[i]] == "all" then
          hasStartedBid[players[i]] = 1
          turn_control.call("add_skip", players[i])
          passCount = passCount + 1
        else
          -- table index is nil?
          hasStartedBid[players[i]] = 0
        end
      end
    end

    -- set the next turns as the person who needs to bid next
    local order_player = turn_control.call("get_order_player")
    for n = 1, #order_player do
      if hasStartedBid[order_player[n]] == 0 then
        turn_control.call("set_turn", order_player[n])
        break
      end
    end

    -- reset variables
    bid = bid_round
    bid_object = nil
    bidder = nil

    collider_board.UI.setAttribute("discovery_bid", "text", "Bid: 0")

    for color, val in pairs(passes) do
      if val == "round" then
        passes[color] = "none"
      end
    end
  else
    -- sets next turn, should auto figure it out based on passes
    turn_control.call("next_turn")
  end

  if discovery_zone.getObjects() == nil then
    Global.call("endPhase")
  elseif passCount == #players then
    -- discovery phase is over, perform cleanup
    local discovery_zone = getObjectFromGUID("6c7a71")
    local cards = discovery_zone.getObjects()
    --all players are turned back on in the turn system
    local player_order = Global.getVar("player_order")
    turn_control.call("clear_skip")

    sendToDiscard(cards)
    Global.call("endPhase")
  end
end

--sends an array of cards to the discard pile
-- the array can include decks
-- will ignore cards that are not of type particle or quest
-- runtime O(n^2)
function sendToDiscard(cards)
  for i = 1, #cards do
    local card = cards[i]
    Wait.time(
      function()
        if card.type == "Deck" then
          for key, value in pairs(card.getObjects()) do
            if #card.getObjects() >= 2 then
              discardDeckCard(card, value)
            else
              local final_card = getObjectFromGUID(value.guid)
              discardCard(final_card)
            end
          end
        elseif card.type == "Card" then
          discardCard(card)
        end
        end, i
      )
    end
  end


  function discardCard(card)
    local particle_discard = Global.getVar("particle_discard_zone")
    local quest1_discard = Global.getVar("quest1_discard_zone")
    local quest2_discard = Global.getVar("quest2_discard_zone")
    if card.memo == "particle" then
      card.setRotation(particle_discard.getRotation())
      card.setPositionSmooth(particle_discard.getPosition())
    elseif card.memo == "quest_one" then
      card.setRotation(quest1_discard.getRotation())
      card.setPositionSmooth(quest1_discard.getPosition())
    elseif card.memo == "quest_two" then
      card.setRotation(quest2_discard.getRotation())
      card.setPositionSmooth(quest2_discard.getPosition())
    end
  end

  -- does not work for decks
  function discardDeckCard(deck, card)
    local particle_discard = Global.getVar("particle_discard_zone")
    local quest1_discard = Global.getVar("quest1_discard_zone")
    local quest2_discard = Global.getVar("quest2_discard_zone")
    if card.memo == "particle" then
      deck.takeObject({
        position = particle_discard.getPosition(),
        rotation = particle_discard.getRotation(),
        smooth = true,
        flip = false,
        guid = card.guid,
      })
    elseif card.memo == "quest_one" then
      deck.takeObject({
        position = quest1_discard.getPosition(),
        rotation = quest1_discard.getRotation(),
        smooth = true,
        flip = false,
        guid = card.guid,
      })
    elseif card.memo == "quest_two" then
      deck.takeObject({
        position = quest2_discard.getPosition(),
        rotation = quest2_discard.getRotation(),
        smooth = true,
        flip = false,
        guid = card.guid,
      })
    end
  end

  --add behavior to handle if there is only one card
  function setupDiscoveryPhase()
    --register player physicist figurines for collisions
    local figurine_guids = Global.getTable("figurine_guids")

    -- register the figurines for collisions to detect bids
    for color, guid in pairs(figurine_guids) do
      getObjectFromGUID(guid).registerCollisions(false)
    end

    local eject_zone = getObjectFromGUID("0cb1ea")
    local eject_deck = createDeck(eject_zone.getObjects())
    local eject_cards = eject_deck.getObjects()
    local collider_board = getObjectFromGUID("1f72b6")
    local rotation = collider_board.getRotation()

    -- quick sort to sort cards by type
    quicksort(eject_cards, 1, #eject_cards, "name")
    -- quick sort cards by pile type (quest1, quest2, particles)
    quicksort(eject_cards, 1, #eject_cards, "memo")

    --set to rotation of collider board
    local prev_card_data = eject_cards[1]
    local prev_card = eject_deck.takeObject({
      position = placement_pos,
      rotation = {0, 90, 0},
      smooth = True,
      guid = prev_card_data.guid,
    })
    local x_mod = 3.2
    local y_mod = 7
    local z_mod = 2

    bid_card_guids[prev_card_data.guid] = prev_card

    -- layout cards on table
    for i = 2, #eject_cards do
      Wait.time(
        function()
          local current_card_data = eject_cards[i]
          if current_card_data == nil then
            return
          end

          bid_card_guids[current_card_data.guid] = current_card_data

          if prev_card_data.name ~= current_card_data.name then
            if placement_pos[3] >= 7.00 then
              placement_pos = {placement_pos[1] + x_mod, placement_pos[2], - y_mod, placement_pos[3]}
            else
              placement_pos = {placement_pos[1], placement_pos[2], placement_pos[3] + z_mod}
            end
          end

          -- deal cards and also accounts for the case when one card is left
          -- and there is no longer a deck to take from

          if i < #eject_cards then
            local current_card = eject_deck.takeObject({
              position = placement_pos,
              rotation = {0, 90, 0},
              smooth = True,
              guid = current_card_data.guid,
            })
            prev_card_data = current_card_data
          else
            local last_card = getObjectFromGUID(current_card_data.guid)
            bid_card_guids[last_card.getGUID()] = last_card
            last_card.setPositionSmooth(placement_pos)
            last_card.setRotationSmooth({0, 90, 0})
          end
        end,
        i * 0.25
      )
    end
  end

  --assumes there will be at least one deck
  -- places any other cards into one main deck
  -- returns the reference to the deck
  function createDeck(objects)
    local master_deck = nil

    for key, value in pairs(objects) do
      if value ~= nil and value.type == "Deck" and value.name ~= "Ejection Pile" then
        master_deck = value
        break
      end
    end

    for key, value in pairs(objects) do
      if value.name ~= "Ejection Pile" and value.guid ~= master_deck.guid then
        if value.type == "Deck" or value.type == "Card" then
          master_deck.putObject(value)
        end
      end
    end
    return master_deck
  end


  function nameCompare(a, b)
    if a.name == b.name or a.name < b.name then
      return True
    else
      return false
    end
  end

  function partition(arr, low, high, type)
    -- sort by name or by type stored in memo
    local pivot = nil

    if type == "name" then
      pivot = arr[high].name
    else
      pivot = arr[high].memo
    end

    local i = (low - 1)

    for j = low, high - 1 do
      local compareVal = nil
      if type == "name" then
        compareVal = arr[j].name
      else
        compareVal = arr[j].memo
      end
      if compareVal <= pivot then
        i = i + 1
        arr[i], arr[j] = arr[j], arr[i]
      end
    end
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return (i + 1)
  end

  function quicksort(arr, low, high, type)
    if low < high then
      local pi = partition(arr, low, high, type)

      quicksort(arr, low, pi - 1, type)
      quicksort(arr, pi + 1, high, type)
    end
    return arr
  end
