local placement_pos = { - 14.50, 0.97, - 7.00}


function onLoad()
  self.createButton({
    click_function = "setupDiscoveryPhase",
    function_owner = self,
    width = 400,
    height = 400
  })
end

--none: player has not passed
--round: player passes on the current bid
--all: player permenantly passed discovery phase
local passes = {
  ["Red"] = "none",
  ["Blue"] = "none",
  ["Green"] = "none",
  ["Yellow"] = "none"
}

local hasStartedBid = {
  ["Red"] = false,
  ["Blue"] = false,
  ["Yellow"] = false,
  ["Green"] = false
}

-- the value of the current bid
local bid = 1
-- the color of the player with highest bid
local bidder = nil
-- the round number which only increases after each player gets to bid once
-- controls the cost of starting bids
local bid_round = 1
-- the card being bid upon
local bid_object = nil
local collider_board = nil
local bid_card_guids = {}
local score_button = nil

--checks if player has the money and it is their bid turn, then increases the bid by +1
function increaseBid(player)
  local current_phase = Global.getVar("current_phase")
  if current_phase == 4 then
    local player_color = player.color
    local player_coins = score_button.call("calculateCoins", player_color)

    if player_color ~= bidder then
      broadcastToAll(player_color.. ". It is not your turn to increase the bid or you haven't placed your physicist on a card yet!")
    end

    if player_coins >= bid + 1 then
      bid = bid + 1
      collider_board.UI.setAttribute("discovery_bid", "text", "Bid: " ..bid)
    else
      broadcastToAll(player_color.. ". You do not have enough coins to make this increased bid!")
    end
  else
    broadcastToAll("Wrong phase, this button should not be available to you!")
  end

end

--called when a player clicks a pass button
-- type: the pass type "round" or "all"
function playerPass(player, type)
  local collider_board = getObjectFromGUID("1f72b6")

  --reset everything if bidder is passing
  if player.color == bidder then
    bid = bid_round
    bidder = nil
    bid_object = nil
    collider_board.call("kickLowerBid", player.color)
  end

  local current_phase = Global.getVar("current_phase")
  if current_phase == 4 then
    passes[player.color] = type
    attemptEndBid()
  else
    broadcastToAll("Wrong phase, this button should not be available to you!")
  end
end

local bid_setup = false
--if its a deck take the card
-- collision {["color"] = , ["object"] =}
function calculateBid(collision)
  -- deal with re-trigger from moving card to bid position
  if bid_setup then
    bid_setup = false
    return
  end

  local bid_card_pos = { - 18.7, 1, 0}

  local player_color = collision["player_color"]
  local object = collision["object"]
  local figurine_guids = Global.getTable("figurine_guids")
  local physicist = getObjectFromGUID(figurine_guids[player_color])

  -- exit the function if player is just moving figurine on the card
  if bidder == player_color then
    return
  end

  -- prevent player from bidding on their own cards or game decks
  if object.type == "Deck" then
    --if its a Deck we fetch the GUID of the first item
    if bid_card_guids[object.getObjects()[1].guid] == nil then
      broadcastToAll("You cannot bid on this card/deck!")
      return
    end
  else
    if bid_card_guids[object.getGUID()] == nil then
      broadcastToAll("You cannot bid on this card/deck!")
      return
    end
  end

  local bid_card = nil;
  -- set bid_card to bid_object
  if bid_object ~= nil then
    bid_card = bid_object
  end

  -- if no bid is set, get the bid_object and set it, move card to bid location
  if bid_object == nil then
    if object ~= nil and object.type == "Deck" then
      bid_card = object.takeObject({
        position = bid_card_pos,
        smooth = true,
      })
    else
      bid_card = object
      bid_card.setPositionSmooth(bid_card_pos)
    end
    bid_setup = true
    physicist.setPositionSmooth({bid_card_pos[1], 2, bid_card_pos[3]})
  end

  --if its initial setup we set the bid_object
  if bid_object == nil then
    bid_object = bid_card
  end


  local current_phase = Global.getVar("current_phase")
  score_button = getObjectFromGUID("652e27")
  local player_coins = score_button.call("calculateCoins", player_color)
  collider_board = getObjectFromGUID("1f72b6")

  --this error will likely never happen
  -- if round is Discovery Round
  --if current_phase ~= 4 then
  --broadcastToAll("It is not the Discovery phase, you cannot bid on ejection cards!")
  --return
  --end

  --check to make sure the player can afford the bid they're making
  if player_coins < bid + 1 then
    local type = "bid"
    if passes[player_color] == "none" then
      if player_coins < bid_round + 1 then
        passes[player_color] = "all"
        type = "ejection phase"
      else
        passes[player_color] = "round"
      end
    end
    broadcastToAll("You do not have enough coins to bid. You will be automatically passed for this " ..type)
    collider_board.call("kickLowerBid", player_color)
    return
  end

  --check to ensure the correct card is being bid on
  if bid_object.getName() == bid_card.getName() then
    --if a new player is bidding and hasn't passed
    if player_color ~= bidder and passes[player_color] == "none" then
      -- kick other bid figurine (physicist)
      if bidder ~= nil then
        collider_board.call("kickLowerBid", bidder)
      end

      bidder = player_color
      bid = bid + 1
      collider_board.UI.setAttribute("discovery_bid", "text", "Bid: " ..bid)

      attemptEndBid()
    else
      broadcastToColor("You already have highest bid or have passed this round or you are trying to bid on another card. Only one card bid at a time.", player_color)
    end
  end
end

function attemptEndBid()
  local passCount = 0
  local players = getSeatedPlayers()
  --counting number of players that have passed
  for i = 1, #players do
    local player_color = players[i]
    local pass_value = passes[player_color]
    if pass_value == "all" or pass_value == "round" then
      passCount = passCount + 1
    end
  end

  -- if all but one player has passed complete the bid
  if passCount == #players - 1 then
    --give card to player and reset bid variables
    bid_card_guids[bid_object.getGUID()] = nil
    bid_object.deal(1, bidder)

    collider_board.call("kickLowerBid", bidder)
    collider_board.call("spendCoins", {["cost"] = bid, ["player_color"] = bidder})

    -- reset variables
    bid_round = bid_round + 1
    bid = bid_round
    bid_object = nil
    bidder = "none"

    collider_board.UI.setAttribute("discovery_bid", text, "Bid: 0")

    for color, val in pairs(passes) do
      if val == "round" then
        passes[color] = "none"
      end
    end

  end

  if passCount == #players then
    -- discovery phase is over, perform cleanup
    local discovery_zone = getObjectFromGUID("6c7a71")
    local cards = discovery_zone.getObjects()
    sendToDiscard(cards)
  end
end

--sends an array of cards to the discard pile
-- the array can include decks
-- will ignore cards that are not of type particle or quest
-- runtime O(n^2)
function sendToDiscard(cards)
  local particle_discard = Global.getTable("particle_discard_zone")
  local quest1_discard = Global.getVar("quest1_discard_zone")
  local quest2_discard = Global.getVar("quest2_discard_zone")

  for i = 1, #cards do
    local card = cards[i]
    if card.type == "Deck" then
      sendToDiscard(card.getObjects())
    elseif card.type == "Card" then
      if card.memo == "particle" then
        card.setRotation(particle_discard.getRotation())
        card.setPositionSmooth(particle_discard.getPosition())
      elseif card.memo == "quest_one" then
        card.setRotation(quest1_discard.getRotation())
        card.setPositionSmooth(quest1_discard.getPosition())
      elseif card.memo == "quest_two" then
        card.setRotation(quest2_discard.getRotation())
        card.setPositionSmooth(quest2_discard.getPosition())
      end
    end
  end
end

--add behavior to handle if there is only one card
function setupDiscoveryPhase()
  --register player physicist figurines for collisions
  local figurine_guids = Global.getTable("figurine_guids")

  for color, guid in pairs(figurine_guids) do
    getObjectFromGUID(guid).registerCollisions(false)
  end

  local eject_zone = getObjectFromGUID("0cb1ea")
  local eject_deck = createDeck(eject_zone.getObjects())
  local eject_cards = eject_deck.getObjects()
  local collider_board = getObjectFromGUID("1f72b6")
  local rotation = collider_board.getRotation()

  -- quick sort to sort cards by type
  quicksort(eject_cards, 1, #eject_cards, "name")
  -- quick sort cards by pile type
  quicksort(eject_cards, 1, #eject_cards, "memo")

  --set to rotation of collider board
  local prev_card_data = eject_cards[1]
  local prev_card = eject_deck.takeObject({
    position = placement_pos,
    rotation = {0, 90, 0},
    smooth = True,
    guid = prev_card_data.guid,
  })
  local x_mod = 3.2
  local y_mod = 7
  local z_mod = 2

  bid_card_guids[prev_card_data.guid] = prev_card

  -- layout cards on table and register for collision to control bidding
  for i = 2, #eject_cards do
    local current_card_data = eject_cards[i]
    if current_card_data == nil then
      return
    end

    bid_card_guids[current_card_data.guid] = current_card_data

    if prev_card_data.name ~= current_card_data.name then
      if placement_pos[3] >= 7.00 then
        placement_pos = {placement_pos[1] + x_mod, placement_pos[2], - y_mod, placement_pos[3]}
      else
        placement_pos = {placement_pos[1], placement_pos[2], placement_pos[3] + z_mod}
      end
    end

    -- handles case when one card is left and it is no longer a deck
    if i < #eject_cards then
      local current_card = eject_deck.takeObject({
        position = placement_pos,
        rotation = {0, 90, 0},
        smooth = True,
        guid = current_card_data.guid,
      })
      prev_card_data = current_card_data
    else
      local last_card = getObjectFromGUID(current_card_data.guid)
      bid_card_guids[last_card.getGUID()] = last_card
      last_card.setPositionSmooth(placement_pos)
      last_card.setRotationSmooth({0, 90, 0})
    end

  end



end

--assumes there will be at least one deck
-- places any other cards into one main deck
-- returns the reference to the deck
function createDeck(objects)
  local master_deck = nil

  for key, value in pairs(objects) do
    if value ~= nil and value.type == "Deck" and value.name ~= "Ejection Pile" then
      master_deck = value
      break
    end
  end

  for key, value in pairs(objects) do
    if value.name ~= "Ejection Pile" and value.guid ~= master_deck.guid then
      if value.type == "Deck" or value.type == "Card" then
        master_deck.putObject(value)
      end
    end
  end
  return master_deck
end


function nameCompare(a, b)
  if a.name == b.name or a.name < b.name then
    return True
  else
    return false
  end
end

function partition(arr, low, high, type)
  -- sort by name or by type stored in memo
  local pivot = nil

  if type == "name" then
    pivot = arr[high].name
  else
    pivot = arr[high].memo
  end

  local i = (low - 1)

  for j = low, high - 1 do
    local compareVal = nil
    if type == "name" then
      compareVal = arr[j].name
    else
      compareVal = arr[j].memo
    end
    if compareVal <= pivot then
      i = i + 1
      arr[i], arr[j] = arr[j], arr[i]
    end
  end
  arr[i + 1], arr[high] = arr[high], arr[i + 1]
  return (i + 1)
end

function quicksort(arr, low, high, type)
  if low < high then
    local pi = partition(arr, low, high, type)

    quicksort(arr, low, pi - 1, type)
    quicksort(arr, pi + 1, high, type)
  end
  return arr
end
