hotseats = {
  ["Red"] = false,
  ["Green"] = false,
  ["Orange"] = false,
  ["Blue"] = false
}

function onToggleHotseat(player, value, id)
  players = getSeatedPlayers()
  cannotHotseat = "false"
  -- remove hotspot if real player is seated in color
  for i = 1, #players do
    print(id)
    if id == players[i] then
      cannotHotseat = True
    end
  end

  if cannotHotseat == True then
    broadcastToAll("Cannot hotseat " .. id .. " A real player is seated at this seat!")
    print("Cannot hotseat " .. id .. " A real player is seated at this seat!")
    self.UI.setAttribute(id, "isOn", false)
  else
    self.UI.setAttribute(id, "isOn", value)
    hotseats[id] = value
  end
end

function onPlayerChangeColor(player_color)
  --update hotseat board if player changes seats/colors
  hotseats[player_color] = false
  self.UI.setAttribute(player_color, "isOn", false)
end

function getHotseatCount()
  count = 0
  log("hotseats")
  log(hotseats)

  for k,v in pairs(hotseats) do
    log(v)
    if v then
      count = count + 1
    end
  end
  return count
end