--add functionality to flip card for opposite facing players
-- add handler for counting players drawn cards (just recalculate values like ejection cards/etc)
-- add control to prevent people drawing cards out of turn
function onLoad()
  self.memo = "Particle Deck"
end

local min_deck_size = {
  ["Quest 1 Deck"] = {[2] = 5, [3] = 6, [4] = 7},
  ["Quest 2 Deck"] = {[2] = 4, [3] = 5, [4] = 6},
  ["Particle Deck"] = {[2] = 10, [3] = 15, [4] = 15}
}

local deck_discard_guids = {
  ["Quest 1 Deck"] = "a0c4a3",
  ["Quest 2 Deck"] = "4af37c",
  ["Particle Deck"] = "345485"
}

-- keeps an eye on the decks to ensure discards are being shuffled and added back as decks get low in cards
function attemptDeckReshuffle(container)
  -- use putObject
  if container.type == "Deck" then
    local deck_name = container.memo
    local players = getSeatedPlayers()
    if #container.getObjects() <= min_deck_size[deck_name][#players] then
      local discard_zone = getObjectFromGUID(deck_discard_guids[deck_name])
      local discard_objs = discard_zone.getObjects()
      local discard_deck = nil

      for i = 1, #discard_objs do
        if discard_objs[i].type == "Deck" then
          discard_deck = discard_objs[i]
          break
        end
      end

      discard_deck.flip()
      discard_deck.shuffle()
      container.putObject(discard_deck)
    end
  end
end

local main_decks = {
  ["Quest 1 Deck"] = "quest_one",
  ["Quest 2 Deck"] = "quest_two",
  ["Particle Deck"] = "particle",
}

function onObjectLeaveContainer(container, leave_object)

  if leave_object.type == "Card" then
    leave_object.addContextMenuItem("Eject Card", ejectCard)
  end

  container_name = container.memo

  for name, memo in pairs(main_decks) do
    if name == container_name then
      leave_object.memo = memo
      attemptDeckReshuffle(container)
      return
    end
  end

  if container_name == "3 eV" then
    leave_object.memo = "three"
  end

  if container_name == "1 eV" then
    leave_object.memo = "one"
  end

end

local eject_locations = {
  ["Red"] = { - 8.00, 1.00, - 8.00},
  ["Yellow"] = {14.00, 1.00, - 8.00},
  ["Blue"] = {8.00, 1.00, 8.00},
  ["Green"] = { - 14.00, 1.00, 8.00}
}

local ejection_allowances = {
  ["Red"] = 0,
  ["Yellow"] = 0,
  ["Green"] = 0,
  ["Blue"] = 0
}

-- something wrong in this function, triggering twice for first player
function onEjectionPhaseStart()
  local players = getSeatedPlayers()

  for i = 1, #players do
    local player_color = players[i]
    local cards = Player[player_color].getHandObjects()
    local positronium = Global.getTable("multiCardPowers")[player_color]["Positronium"]

    local card_count = 0
    for j = 1, #cards do
      if cards[j].type == "Card" then
        card_count = card_count + 1
      end
    end
    ejection_allowances[player_color] = math.floor(card_count / 5)

    card_count = 0

    local min_ejection = ejection_allowances[player_color] - positronium
    if min_ejection == 0 then
      broadcastToColor("You may eject between 0 and " ..ejection_allowances[player_color].. " card(s).", player_color)
    elseif min_ejection == ejection_allowances[player_color] then
      broadcastToColor("You must eject " .. ejection_allowances[player_color].. " cards.", player_color)
    else
      broadcastToColor("You must eject at least " ..min_ejection.. " card(s). But you can eject up to " ..ejection_allowances[player_color].. " card(s).", player_color)
    end
  end
end

function onEjectionPhaseEnd()
  local positronium = Global.getTable("multiCardPowers")[player_color]["Positronium"]
  local players = getSeatedPlayers()

  local roundEndFail = false

  for i = 1, #players do
    local ejections = ejection_allowances[players[i]]
    if ejections ~= 0 and positronium < ejections then
      broadcastToAll(players[i].. " has not ejected enough cards so the phase cannot be ended!")
      roundEndFail = true
    end
  end

  if foundEndFail == false then
    Global.call("checkForNeutrinos")
  end
end

--add global ejection table to track how many ejects people can do

function ejectCard(player_color, position, object)
  local single_card_powers = Global.getTable("singleCardPowers")
  local down_annihilation_color = single_card_powers["Down Annihilation"]
  local pion_after_eject = single_card_powers["Pion After Eject"]
  local eject_deck = Global.getVar("eject_deck")
  local eject_deck_location = eject_deck.getPosition()

  local zones = object.getZones()
  local phase = Global.getVar("current_phase")
  local round = Global.getVar("current_round")

  if phase ~= 3 then
    broadcastToColor("You cannot eject cards in this phase!", player_color)
    return
  end
  if ejection_allowances[player_color] == 0 and round ~= 5 then
    broadcastToColor("You are not allowed to eject any more cards", player_color)
    return
  end

  if inHandZone(object, player_color) then
    local one_ev_bag = Global.getVar("one_ev_bag")
    local coin_boards = Global.getTable("coin_board_guids")
    ejection_allowances[player_color] = ejection_allowances[player_color] - 1

    --remove from hand instantly
    object.setRotation({0, 180, 180})
    object.setPosition(eject_locations[player_color])
    --set location again for smooth animation
    object.setPositionSmooth({eject_deck_location[1], 2, eject_deck_location[3]})

    --one coin per card ejected
    --only pay out coins when ejections are complete??
    --Make use of deal card generic function
    local one_ev_bag = Global.getVar("one_ev_bag")
    if down_annihilation_color == player_color then
      one_ev_bag.call("dealCoins", {["value"] = 2, ["player_color"] = player_color})
    else
      one_ev_bag.call("dealCoins", {["value"] = 1, ["player_color"] = player_color})
    end

    local ejections_remaining = ejection_allowances["Yellow"] + ejection_allowances["Blue"] + ejection_allowances["Green"] + ejection_allowances["Red"]

    if ejections_remaining == 0 then
      ejectionEndSteps()
    end

  else
    print("You can only eject cards in your hand!")
  end
end

function ejectionEndSteps()
  local players = getSeatedPlayers()

  for i = 1, #players do
    local player_color = players[i]
    if pion_after_eject == player_color then
      local round = Global.getVar("current_round")
      local draw_amount = math.floor(round / 2)
      broadcastToAll(player_color.. " must draw " ..draw_amount.. " card(s) before the round ends.")
      --exit function so round doesn't end until cards are drawn
      return
    end
  end

  --if we are not waiting for the player with pion_after_eject card
  -- to draw extra cards then we end the round
  Wait.time(
    function()
      Global.setVar("neutrinosEndRound", true)
      Global.call("checkForNeutrinos")
    end, 2)
  end

  --checks if the ejection card is in the hand zone of the correct person
  function inHandZone(object, ejectColor)
    local zones = object.getZones()
    for i = 1, #zones do
      local zone = zones[i]
      if zone.type == "Hand" and ejectColor == zone.getData()["FogColor"] then
        return true
      end
    end
    return false
  end
