--add functionality to flip card for opposite facing players
-- add handler for counting players drawn cards (just recalculate values like ejection cards/etc)
-- add control to prevent people drawing cards out of turn
local turn_control = nil

local players = {}

local buy_card = nil

function onLoad()
  self.memo = "Particle Deck"
  turn_control = getObjectFromGUID("90061a")
  players = Global.call("getPlayers")
  buy_card = Global.getVar("buy_card")
end

function onPlayerChangeColor( player_color)
  players = Global.call("getPlayers")
end

local min_deck_size = {
  ["Quest 1 Deck"] = {[2] = 5, [3] = 6, [4] = 7},
  ["Quest 2 Deck"] = {[2] = 4, [3] = 5, [4] = 6},
  ["Particle Deck"] = {[2] = 10, [3] = 15, [4] = 15}
}

local deck_discard_guids = {
  ["Quest 1 Deck"] = "a0c4a3",
  ["Quest 2 Deck"] = "4af37c",
  ["Particle Deck"] = "345485"
}

-- keeps an eye on the decks to ensure discards are being shuffled and added back as decks get low in cards
function attemptDeckReshuffle(container)
  -- use putObject
  if container == nil then return end
  if container.type == "Deck" then
    local deck_name = container.memo
    if #container.getObjects() <= min_deck_size[deck_name][#players] then
      local discard_zone = getObjectFromGUID(deck_discard_guids[deck_name])
      if discard_zone.getObjects() == nil then
        -- if there are no objects in the discard zone can't reshuffle
        return
      end
      local discard_objs = discard_zone.getObjects()
      local discard_deck = nil

      for i = 1, #discard_objs do
        if discard_objs[i].type == "Deck" then
          discard_deck = discard_objs[i]
          break
        end
      end

      discard_deck.flip()
      discard_deck.shuffle()
      container.putObject(discard_deck)
    end
  end
end

local main_decks = {
  ["Quest 1 Deck"] = "quest_one",
  ["Quest 2 Deck"] = "quest_two",
  ["Particle Deck"] = "particle",
}

function onObjectLeaveContainer(container, leave_object)
  if leave_object.type == "Card" then
    leave_object.addContextMenuItem("Eject Card", ejectCard)
    leave_object.addContextMenuItem("Discard", discardCard)
  end

  local container_name = container.memo

  for name, memo in pairs(main_decks) do
    if name == container_name then
      leave_object.memo = memo
      attemptDeckReshuffle(container)
      return
    end
  end

  if container_name == "3 eV" then
    leave_object.memo = "three"
  end

  if container_name == "1 eV" then
    leave_object.memo = "one"
  end

end

local eject_locations = {
  ["Red"] = { - 8.00, 1.00, - 8.00},
  ["Yellow"] = {14.00, 1.00, - 8.00},
  ["Blue"] = {8.00, 1.00, 8.00},
  ["Green"] = { - 14.00, 1.00, 8.00}
}

ejection_allowances = {
  ["Red"] = 0,
  ["Yellow"] = 0,
  ["Green"] = 0,
  ["Blue"] = 0
}

-- something wrong in this function, triggering twice for first player
function onEjectionPhaseStart()
  local selection_cards = Global.getTable("selection_cards")
  local neutrinos_in_hand = Global.getTable("neutrinos_in_hand")

  for i = 1, #players do
    local player_color = players[i]
    local cards = Player[player_color].getHandObjects()
    local positronium = Global.getTable("multiCardPowers")[player_color]["Positronium"]
    local pion_before_eject = Global.getTable("singleCardPowers")["Pion Before Eject"]
    local current_round = Global.getVar("current_round")

    local card_count = 0
    for j = 1, #cards do
      if cards[j].type == "Card" then
        card_count = card_count + 1
      end
    end

    --account for extra draws player will get with before eject Pion
    if pion_before_eject ~= "none" and pion_before_eject == player_color then
      card_count = card_count + math.floor(current_round / 2)
      broadcastToColor("You get to draw " .. math.floor(current_round / 2) .. " due to your completed pion.", player_color)
    end

    if selection_cards[player_color] ~= nil and #selection_cards[player_color] > 0 then
      card_count = card_count + 1
    end

    -- also count neutrinos not yet resolved (not in hand)
    if neutrinos_in_hand[player_color] ~= nil and #neutrinos_in_hand[player_color] > 0 then
      card_count = card_count + #neutrinos_in_hand[player_color]
    end

    ejection_allowances[player_color] = math.floor(card_count / 5)

    card_count = 0

    if current_round == 5 then
      broadcastToAll("Final round, no ejection limits!")
    end

    local min_ejection = ejection_allowances[player_color] - (positronium * 2) --2 less cards to eject per positronium
    if min_ejection <= 0 then
      if ejection_allowances[player_color] == 0 then
        broadcastToColor("Ejection Phase: You do not eject any cards.", player_color)
      else
        broadcastToColor("Ejection Phase: You may eject between 0 and " ..ejection_allowances[player_color].. " card(s).", player_color)
      end
    elseif min_ejection == ejection_allowances[player_color] then
      broadcastToColor("Ejection Phase: You must eject " .. ejection_allowances[player_color].. " cards.", player_color)
    else
      broadcastToColor("Ejection Phase: You must eject at least " ..min_ejection.. " card(s). But you can eject up to " ..ejection_allowances[player_color].. " card(s).", player_color)
    end


  end
end

function setEjectionsToZero(player)
  local positronium = Global.getTable("multiCardPowers")[player.color]["Positronium"]
  if ejection_allowances[player.color] - positronium > 0 then
    broadcastToColor("You have not ejected enough cards. You cannot end your turn.", player.color)
    return
  else
    ejection_allowances[player.color] = 0
  end

  local ejections_remaining = ejection_allowances["Yellow"] + ejection_allowances["Blue"] + ejection_allowances["Green"] + ejection_allowances["Red"]

  if ejections_remaining == 0 then
    ejectionEndSteps()
  else
    turn_control.call("next_turn")
  end
end

function onEjectionPhaseEnd()
  local roundEndFail = false

  for i = 1, #players do
    local player_color = players[i]
    local positronium = Global.getTable("multiCardPowers")[player_color]["Positronium"]
    local ejections = ejection_allowances[players[i]]
    if ejections ~= 0 and positronium < ejections then
      broadcastToAll(players[i].. " has not ejected enough cards so the phase cannot be ended!")
      roundEndFail = true
    end
  end

  if roundEndFail == false then
    Global.UI.setAttributes("end_eject", {active = false, visibility = "hidden"})
    Global.UI.setAttribute("turn_panel", "active", true)
    Global.call("checkForNeutrinos")
  end
end


--allow player to discard cards using context menu
function discardCard(player_color, position, card)
  local pos = nil
  local rot = nil
  -- discard areas
  local particle_discard = Global.getVar("particle_discard_zone")
  local quest_one_discard = Global.getVar("quest1_discard_zone")
  local quest_two_discard = Global.getVar("quest2_discard_zone")
  if card.memo == 'particle' then
    pos = particle_discard.getPosition()
    rot = particle_discard.getRotation()
  end
  if card.memo == "quest_one" then
    pos = quest_one_discard.getPosition()
    rot = quest_one_discard.getRotation()
  end
  if card.memo == "quest_two" then
    pos = quest_two_discard.getPosition()
    rot = quest_two_discard.getRotation()
  end

  local build_board_guids = Global.getTable("build_board_guids")
  local build_board = getObjectFromGUID(build_board_guids[player_color])
  local build_pos = build_board.getPosition()
  local build_rot = build_board.getRotation()

  local x_mod = 6
  local y_height = pos["y"] + 1
  local z_mod = - 6

  if player_color == "Red" or player_color == "Yellow" then
    z_mod = 6
    x_mod = - 6
  end

  if card ~= nil then
    --place cards in front of user first
    Wait.time( function()
      card.setPosition({build_pos["x"] + x_mod, y_height, build_pos["z"] + z_mod})
      card.setRotation({build_rot["x"], build_rot["y"], 0})
    end,
    0.25
  )

  --then send cards to discard piles
  Wait.time( function()
    card.setPositionSmooth(pos)
    card.setRotationSmooth(rot)
    end, 0.5
  )
end


end

--add global ejection table to track how many ejects people can do
function ejectCard(player_color, position, object)
local single_card_powers = Global.getTable("singleCardPowers")
local down_annihilation_color = single_card_powers["Down Annihilation"]
local eject_zone = getObjectFromGUID("0cb1ea")
local eject_zone_location = eject_zone.getPosition()

local zones = object.getZones()
local phase = Global.getVar("current_phase")
local round = Global.getVar("current_round")

local current_turn = turn_control.call("get_current_turn")
if player_color ~= current_turn then
  broadcastToColor("It is not your turn to eject!", player_color)
  return
end

if phase ~= 3 then
  broadcastToColor("You cannot eject cards in this phase!", player_color)
  return
end
if ejection_allowances[player_color] == 0 and round ~= 5 then
  broadcastToColor("You are not allowed to eject any more cards", player_color)
  return
end

if inHandZone(object, player_color) then
  local one_ev_bag = Global.getVar("one_ev_bag")
  local coin_boards = Global.getTable("coin_board_guids")
  ejection_allowances[player_color] = ejection_allowances[player_color] - 1

  --remove from hand instantly
  object.setRotation({0, 180, 180})
  object.setPosition(eject_locations[player_color])
  --set location again for smooth animation
  object.setPositionSmooth({eject_zone_location[1], 2, eject_zone_location[3]})

  --one coin per card ejected
  --only pay out coins when ejections are complete??
  --Make use of deal card generic function
  if down_annihilation_color == player_color then
    one_ev_bag.call("dealCoins", {["value"] = 2, ["player_color"] = player_color})
  else
    one_ev_bag.call("dealCoins", {["value"] = 1, ["player_color"] = player_color})
  end

else
  print("You can only eject cards in your hand!")
end
end

function ejectionEndSteps()
broadcastToAll("Discovery Phase starting please wait.")
Wait.time(
  function()
    Global.setVar("neutrinosEndRound", true)
    Global.call("checkForNeutrinos")
  end, 2)
end

--checks if the ejection card is in the hand zone of the correct person
function inHandZone(object, ejectColor)
  local zones = object.getZones()
  for i = 1, #zones do
    local zone = zones[i]
    if zone.type == "Hand" and ejectColor == zone.getData()["FogColor"] then
      return true
    end
  end
  return false
end