-- simple helper function to update the users display of their current money (eV)
function updateCoinText(value)
  self.UI.setAttribute("red_coins", "text", value .." eV")
end

local coin_zone_guids = nil
local zone = nil

function onLoad()
  self.interactable = false
  self.registerCollisions(false)
  coin_zone_guids = Global.getTable("coin_zone_guids")
  zone = getObjectFromGUID(coin_zone_guids["Red"])
end

function onCollisionEnter(collision_info)
  Global.call("updateScore", {["zone"] = zone, ["object"] = collision_info.collision_object, ["state"] = "none"})
end

function onCollisionExit(collision_info)
  Global.call("updateScore", {["zone"] = zone, ["object"] = collision_info.collision_object, ["state"] = "none"})
end
