one_ev = nil
three_ev = nil
coin_zones = nil

function onLoad()
  params = {
    click_function = "start_game",
    function_owner = self,
    position = {0, 1, 0},
    rotation = {0, 180, 0},
    width = 1200,
    height = 1500,
    color = {0.5, 0.5, 0.5, 0},
    tooltip = "Start the game.",
  }
  self.createButton(params)

  one_ev = getObjectFromGUID("d98962")
  three_ev = getObjectFromGUID("66bc96")
  coin_zones = Global.getTable("coin_zone_guids")
end

function start_game()
  starting_card = getObjectFromGUID("de36d4")
  players = getSeatedPlayers()

  Turns.enable = true
  Turns.type = 1

  -- select a first player
  number = math.random(1, #players)
  first_player = players[number]
  Global.setVar("starting_physicist", first_player)
  Turns.turn_color = first_player
  starting_card_positions = Global.getTable("starting_card_positions")
  starting_card.setPositionSmooth(starting_card_positions[first_player])

  players = getSeatedPlayers()
  particles = Global.getVar("particles_deck")
  round_cube = getObjectFromGUID("e19c46")
  phase_cube = getObjectFromGUID("1050fc")
  pos = getObjectFromGUID("1f72b6").getPosition()

  round_cube.setPosition({pos[1] - 3.02, pos[2] + 1, pos[3] - 5.28})
  phase_cube.setPosition({pos[1] - 3.02, pos[2] + 1, pos[3] + 2.91})
  UI.setAttribute("round_tracker", "text", "Round 1: Funding Phase")

  if #players <= 1 then
    broadcastToAll("Not enough seated players!")
    return
  else
    Global.call("setNeutrinosEndRound", true)
      initial_setup(particles)
    end

    if #players == 2 then
      Wait.time(
        function()
          deal_coins(particles, True)
        end, 1)
        Wait.time(
          function()
            board.call("two_player_deal")
          end, 2)
        end

        if (#players == 3) or (#players == 4) then
          Wait.time(
            function()
              board.call("four_player_deal")
            end, 1)

            Wait.time(
              function()
                deal_coins(particles, false)
              end
            , 2)
          end
        end

        function initial_setup(particles)
          -- deal out cards and quest to people
          particles.shuffle()
          particles.deal(3)
          quest_one = getObjectFromGUID("4ebb58")
          quest_one.shuffle()
          quest_one.deal(1)
          board = getObjectFromGUID("1f72b6")


          --shuffling quest 2 deck
          getObjectFromGUID("a5d775").shuffle()

          -- resolve Neutrinos, end phase after this action
          Wait.time(
            function()
              Global.call("checkForNeutrinos")
            end, 5)
          end

          function deal_coins(particles, isTwoPlayer)

            --places starting money in coin areas
            coin_guids = Global.getTable("coin_board_guids")
            players = getSeatedPlayers()
            for i = 1, #players do
              coin_area = getObjectFromGUID(coin_guids[players[i]])
              pos = coin_area.getPosition()
              x_mod = 1.5
              y = pos["y"] + 1
              z_mod = pos["z"] + 1.5

              one_ev.takeObject({
                position = {pos["x"] - x_mod, y, pos["z"]}
              })
              one_ev.takeObject({
                position = {pos["x"], y, pos["z"]}
              })
              if isTwoPlayer ~= True then
                one_ev.takeObject({
                  position = {pos["x"] + x_mod, y, pos["z"]}
                })
                three_ev.takeObject({
                  position = {pos["x"] + x_mod, y, z_mod}
                })
              end
              three_ev.takeObject({
                position = {pos["x"] - x_mod, y, z_mod}
              })
              three_ev.takeObject({
                position = {pos["x"], y, z_mod}
              })

              Wait.time(function()
                self.destruct()
              end, 7)

            end
          end