function onLoad()
  params = {
    click_function = "start_game",
    function_owner = self,
    position = {0, 1, 0},
    rotation = {0, 180, 0},
    width = 1200,
    height = 1500,
    color = {0.5, 0.5, 0.5, 0},
    tooltip = "Start the game.",
  }
  self.createButton(params)
end

local turn_order = {
  ["Red"] = 1,
  ["Green"] = 2,
  ["Blue"] = 3,
  ["Yellow"] = 4
}

function start_game()
  local starting_card = getObjectFromGUID("de36d4")
  local players = getSeatedPlayers()

  table.sort(players,
    function(a, b)
      return turn_order[a] < turn_order[b]
  end)

  local player_index = {}
  local index_player = {}
  for i = 1, #players do
    player_index[players[i]] = i
    index_player[i] = players[i]
  end

  Global.setTable("player_index", player_index)
  Global.setTable("index_player", index_player)
  Global.setTable("player_order", players)

  Turns.enable = true
  Turns.type = 1
  Turns.order = players

  -- randomly select a first player
  number = math.random(1, #players)
  first_player = players[number]
  Global.setVar("starting_physicist", first_player)
  Turns.turn_color = first_player

  starting_card_positions = Global.getTable("starting_card_positions")
  starting_card.setPositionSmooth(starting_card_positions[first_player])

  particles = Global.getVar("particles_deck")
  round_die = Global.getVar("round_die")
  phase_die = Global.getVar("phase_die")
  pos = Global.getVar("collider_board").getPosition()

  round_die.setPosition({pos[1] - 3.02, pos[2] + 1, pos[3] - 5.28})
  phase_die.setPosition({pos[1] - 3.02, pos[2] + 1, pos[3] + 2.91})
  UI.setAttribute("round_tracker", "text", "Round 1: Funding Phase")

  if #players <= 1 then
    broadcastToAll("Not enough seated players!")
    return
  else
    Global.setVar("neutrinosEndRound", true)
    initial_setup(particles)
  end

  if #players == 2 then
    Wait.time(
      function()
        deal_coins(particles, True)
      end
    , 1)
    Wait.time(
      function()
        board.call("two_player_deal")
      end
    , 2)
  end

  if (#players == 3) or (#players == 4) then
    Wait.time(
      function()
        board.call("four_player_deal")
      end
    , 1)

    Wait.time(
      function()
        deal_coins(particles, false)
      end
    , 2)
  end
end

function initial_setup(particles)
  -- deal out cards and quest to people
  particles.shuffle()
  particles.deal(3)
  quest_one = Global.getVar("quest1_deck")
  quest_one.shuffle()
  quest_one.deal(1)
  board = Global.getVar("collider_board")


  --shuffling quest 2 deck
  local quest_two = Global.getVar("quest2_deck")
  quest_two.shuffle()

  -- resolve Neutrinos, end phase after this action
  Wait.time(
    function()
      Global.call("checkForNeutrinos")
    end
  , 5)
end

function deal_coins(particles, isTwoPlayer)
  local one_ev = Global.getVar("one_ev_bag")
  local three_ev = Global.getVar("three_ev_bag")

  --places starting money in coin areas
  coin_guids = Global.getTable("coin_board_guids")
  players = getSeatedPlayers()
  for i = 1, #players do
    coin_area = getObjectFromGUID(coin_guids[players[i]])
    pos = coin_area.getPosition()
    x_mod = 1.5
    y = pos["y"] + 1
    z_mod = pos["z"] + 1.5

    one_ev.takeObject({
      position = {pos["x"] - x_mod, y, pos["z"]}
    })
    one_ev.takeObject({
      position = {pos["x"], y, pos["z"]}
    })
    if isTwoPlayer ~= True then
      one_ev.takeObject({
        position = {pos["x"] + x_mod, y, pos["z"]}
      })
      three_ev.takeObject({
        position = {pos["x"] + x_mod, y, z_mod}
      })
    end
    three_ev.takeObject({
      position = {pos["x"] - x_mod, y, z_mod}
    })
    three_ev.takeObject({
      position = {pos["x"], y, z_mod}
    })

    Wait.time(function()
      self.destruct()
    end, 7)

  end
end
