

local player_order = {}
local order_player = {}
local current_turn = "none"
local num_order = {[1] = "Red", [2] = "Green", [3] = "Blue", [4] = "Yellow"}
local order_num = {["Red"] = 1, ["Green"] = 2, ["Blue"] = 3, ["Yellow"] = 4}
local skip_player = {}
local player_count = 0

function onLoad()
  self.interactable = false
end

function initiate_turns()
  local players = getSeatedPlayers()
  player_count = #players

  table.sort(players,
    function (a, b)
      return order_num[a] < order_num[b]
    end
  )

  for i = 1, #players do
    player_order[players[i]] = i
    order_player[i] = players[i]
    skip_player[players[i]] = "none"
  end

  local start_num = math.random(1, #players)
  current_turn = order_player[start_num]
  update_turn_ui(current_turn)
end

function get_current_turn()
  return current_turn
end

function add_skip(player_color)
  local players = getSeatedPlayers()
  if count_skips() < #players then
    skip_player[player_color] = "skip"
  end
end

function count_skips()
  local count = 0
  for i = 0, #order_player do
    if skip_player[order_player[i]] == "skip" then
      count = count + 1
    end
  end
  return count
end

function remove_skip(player_color)
  skip_player[player_color] = "none"
end

function clear_skip()
  local players = getSeatedPlayers()
  for i = 0, #players do
    skip_player[players[i]] = "none"
  end
end

function next_turn()
  -- setup checks for end of array
  local index = player_order[current_turn]

  --check for skipped players and progress to a player who hasn't been skipped
  -- break the array when a non-skipped player is found and set that player
  for i = 1, player_count do
    if index < player_count then
      index = index + 1
    else
      index = 1
    end

    if skip_player[order_player[index]] == "none" then
      break
    end
  end

  current_turn = order_player[index]
  update_turn_ui(current_turn)

  return order_player[index]
end

function set_turn(player_color)
  if skip_player[player_color] == "none" then
    current_turn = player_color
    update_turn_ui(current_turn)
  else
    print("This player has been skipped, cannot set turn.")
  end
end

function update_turn_ui(player_color)
  local players = getSeatedPlayers()
  local visibility_set = ""
  for i = 1, #players do
    if players[i] == player_color then
      table.remove(players, i)
      Global.UI.setAttributes("change_turn", {visibility = player_color, active = true})
      break
    end
  end
  -- create visiblity set for XML UI element
  for j = 1, #players do
    if j == 1 then
      visibility_set = visibility_set .. players[j]
    else
      visibility_set = visibility_set .. "|" .. players[j]
    end
  end
  Global.UI.setAttributes("turn_indicator", {color = player_color, text = player_color .. "'s Turn", active = true, visibility = visibility_set})
end